# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

std_setdiff <- function(x, y) {
    .Call(`_RMR_ICP_std_setdiff`, x, y)
}

LDclump <- function(R, ld_r2_thresh) {
    .Call(`_RMR_ICP_LDclump`, R, ld_r2_thresh)
}

blockinffun <- function(F4gammah) {
    .Call(`_RMR_ICP_blockinffun`, F4gammah)
}

LDclumpfun <- function(F4gammah, F4Gammah, F4se1, F4se2, F4Rblock, ld_r2_thresh) {
    .Call(`_RMR_ICP_LDclumpfun`, F4gammah, F4Gammah, F4se1, F4se2, F4Rblock, ld_r2_thresh)
}

blockfun <- function(NB) {
    .Call(`_RMR_ICP_blockfun`, NB)
}

normal_pdf <- function(x, m, s) {
    .Call(`_RMR_ICP_normal_pdf`, x, m, s)
}

RMRICPindep <- function(gammah, Gammah, se1, se2, opts = NULL) {
    .Call(`_RMR_ICP_RMRICPindep`, gammah, Gammah, se1, se2, opts)
}

RMRICPSim <- function(gammah, Gammah, se1, se2, R, block_inf, opts = NULL) {
    .Call(`_RMR_ICP_RMRICPSim`, gammah, Gammah, se1, se2, R, block_inf, opts)
}

RMRICP <- function(F4gammah, F4Gammah, F4se1, F4se2, F4Rblock, opts = NULL) {
    .Call(`_RMR_ICP_RMRICP`, F4gammah, F4Gammah, F4se1, F4se2, F4Rblock, opts)
}

Cal_block_SimR <- function(block_inf, X, lam) {
    .Call(`_RMR_ICP_Cal_block_SimR`, block_inf, X, lam)
}

fastSigLm <- function(y, X) {
    .Call(`_RMR_ICP_fastSigLm`, y, X)
}

rcpparma_hello_world <- function() {
    .Call(`_RMR_ICP_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_RMR_ICP_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_RMR_ICP_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_RMR_ICP_rcpparma_bothproducts`, x)
}

